<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonRelyOn\CommonRelyOn.csproj" />
    <ProjectReference Include="..\Keystone.Infrastructure\Keystone.Infrastructure.csproj" />
    <ProjectReference Include="..\Keystone.Model\Keystone.Model.csproj" />
  </ItemGroup>

</Project>
