<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonRelyOn\CommonRelyOn.csproj" />
    <ProjectReference Include="..\SkyFrpPanel.Common\SkyFrpPanel.Common.csproj" />
    <ProjectReference Include="..\SkyFrpPanel.ServiceCore\SkyFrpPanel.ServiceCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Content\IService\" />
    <Folder Include="Public\IPublicService\" />
  </ItemGroup>

</Project>
