<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <!--<Nullable>enable</Nullable>-->
	  <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>3a9c340f-6c61-418c-b8a4-7bb4013d1d5f</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonRelyOn\CommonRelyOn.csproj" />
    <ProjectReference Include="..\SkyFrpPanel.CodeGenerator\SkyFrpPanel.CodeGenerator.csproj" />
    <ProjectReference Include="..\SkyFrpPanel.Mall\SkyFrpPanel.Mall.csproj" />
    <ProjectReference Include="..\SkyFrpPanel.Service\SkyFrpPanel.Service.csproj" />
    <ProjectReference Include="..\SkyFrpPanel.Tasks\SkyFrpPanel.Tasks.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\Content\" />
    <Folder Include="Controllers\File\" />
    <Folder Include="Controllers\Public\" />
    <Folder Include="data\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ip2region.xdb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
