<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonRelyOn\CommonRelyOn.csproj" />
    <ProjectReference Include="..\SkyFrpPanel.Model\SkyFrpPanel.Model.csproj" />
    <ProjectReference Include="..\SkyFrpPanel.Service\SkyFrpPanel.Service.csproj" />
  </ItemGroup>

</Project>
