<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="Model\Dto\" />
    <Folder Include="Service\IService\" />
  </ItemGroup>

  <ItemGroup>
    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Keystone.Infrastructure\Keystone.Infrastructure.csproj" />
    <ProjectReference Include="..\Keystone.ServiceCore\Keystone.ServiceCore.csproj" />
  </ItemGroup>

</Project>
